### ISSUE TITLE
Multiple alignment runs/settings for a given tool/index

### ISSUE THREAD

**Issue by rsuchecki** [csiro-crop-informatics/biokanga-manuscript#30]
Exploration/comparison of different sets of parameters for a given aligner.

~~One way of doing that is by allowing multiple alignment templates for a given tool while preserving the link to the corresponding index. Index metadata could hold a list of alignment templates. Index item in an channel could be duplicated for each alignment template~~. **Doable but a bit fragile** Labelling would be a problem, perhaps better to do that via config (also run-time input JSON/YAML definition)?

This is basically a nested map where top level key is the tool label, second level map key is a free label and the associated string of params.  For each tool we should have a  `default` which should include all params we use which are not essential to the tool functioning within the framework. We should probably also list the "reserved" params (in/out files, threads, in/out format-related params)

JSON, YAML could be produced as part of the workflow run, then added-to or modified by the user and used with `-params-file` 

Example:

* NF config file

```groovy
params {
  alignersParamsRNA = [
    'biokanga': [
      default: '--mode 0 --pemode 3 --pairmaxlen 100000 --substitutions 5 --minchimeric 50',
      alternative: '--mode 0 --pemode 3 --pairmaxlen 100000 --substitutions 2 --minchimeric 50', 
      another: '--mode 0 --pemode 3 --pairmaxlen 100000 --substitutions 2 --minchimeric 75'
    ],
    'bbmap': [
      default: 'maxindel=100000 ambiguous=best intronlen=20 local=t',
      custom: 'maxindel=200000 ambiguous=best intronlen=20 local=f'
    ] 
  ]
}
```

* JSON

```json
{
    "alignersParamsRNA": {
        "biokanga": {
            "default": "--mode 0 --pemode 3 --pairmaxlen 100000 --substitutions 5 --minchimeric 50",
            "alternative": "--mode 0 --pemode 3 --pairmaxlen 100000 --substitutions 2 --minchimeric 50",
            "another": "--mode 0 --pemode 3 --pairmaxlen 100000 --substitutions 2 --minchimeric 75"
        },
        "bbmap": {
            "default": "maxindel=100000 ambiguous=best intronlen=20 local=t",
            "custom": "maxindel=200000 ambiguous=best intronlen=20 local=f"
        }
    }
}
```
* YAML

```yaml
---
alignersParamsRNA:
  biokanga:
    default: "--mode 0 --pemode 3 --pairmaxlen 100000 --substitutions 5 --minchimeric 50"
    alternative: "--mode 0 --pemode 3 --pairmaxlen 100000 --substitutions 2 --minchimeric 50"
    another: "--mode 0 --pemode 3 --pairmaxlen 100000 --substitutions 2 --minchimeric 75"
  bbmap:
    default: maxindel=100000 ambiguous=best intronlen=20 local=t
    custom: maxindel=200000 ambiguous=best intronlen=20 local=f
```
